version: '3.7'

services:
 alibaba_scrapper:
    build:
        context: .
    env_file:
        - .env 
    environment:
        - SCRAPE_ALIBABA=1
    depends_on:
        - mysqldb
    volumes:
        - ./:/scrapperd
        - "/etc/timezone:/etc/timezone:ro"
        - "/etc/localtime:/etc/localtime:ro"
 snapptrip_scrapper:
    build:
        context: .
    env_file:
        - .env 
    environment:
        - SCRAPE_SNAPPTRIP=1
    depends_on:
        - mysqldb
    volumes:
        - ./:/scrapperd
        - "/etc/timezone:/etc/timezone:ro"
        - "/etc/localtime:/etc/localtime:ro"
#  scrapper:
#   build:
#    context: .
#   env_file:
#    - .env 
#   volumes:
#    - ./:/scrapper
#   depends_on:
#    - mysqldb
#  scrapper:
#   build:
#    context: .
#   env_file:
#    - .env 
#   volumes:
#    - ./:/scrapper
#   depends_on:
#    - mysqldb
 mysqldb:
    image: mysql:5.7
    ports:
        - 3306:3306
    env_file:
        - .env 
    volumes:
        - mysql:/var/lib/mysql
        - mysql_config:/etc/mysql
        - ./initdb:/docker-entrypoint-initdb.d

volumes:
    mysql:
    mysql_config:
