version: '3.7'

x-common_scrapper: &scrapper
  image: erfan123a/hotels_comparison:latest
  env_file:
      - .env
  volumes:
      - ./:/scrapperd
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"

services:

  together-n1:
    <<: *scrapper
    environment:
      - SCRAPE_TOGETHER=1
      - ALIBABA_SCRAPPER_SLEEP_TIME=0
      - ALIBABA_TO_SCRAPE_CITIES=tehran,bandarAbbas